build:
    environment:
        php:
            version: 7.1.*
    tests:
        override:
            -
                command: 'vendor/bin/codecept run --coverage --coverage-xml --coverage-html'
                coverage:
                    file: '/tests/_output/coverage.xml'
                    format: 'php-clover'

filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true
