language: php
php:
  - '7.1'
  - '7.2'

env:
  matrix:
    - COMPOSER_OPTIONS="--prefer-dist"
    - COMPOSER_OPTIONS=""

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install $COMPOSER_OPTIONS
  - php paws-test migrate/up --interactive=0

script:
  - composer ci